# Generated by Django 3.2.6 on 2021-08-08 23:45

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0002_activities_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='grade',
            field=models.IntegerField(default=django.db.models.fields.NullBooleanField),
        ),
    ]
