# Generated by Django 3.2.6 on 2021-08-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0004_alter_submissions_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
