# Generated by Django 3.2.6 on 2021-08-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0006_alter_submissions_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='user_id',
            new_name='user',
        ),
    ]
